"""updated expense members model to include userref

Revision ID: 6371cb78ad60
Revises: 0947f934de7e
Create Date: 2025-07-25 15:30:34.666981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6371cb78ad60'
down_revision = '0947f934de7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_friend', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_friend', ['user_id', 'friend_id'])

    # ### end Alembic commands ###
